/**
 * Store persistant Sidekick (localStorage).
 * Une seule clé "sidekick-data" pour tout effacer facilement.
 *
 * Convention : toutes les infos de tous les modules vivent ici.
 * - Ajouter un module : étendre SidekickData + DEFAULT_SIDEKICK_DATA.
 * - Lire/écrire : useSidekickData() → data.<module>.<slice>, setData(prev => ({ ...prev, <module>: { ... } })).
 * - Reset : "npm run reset-data".
 */

export const SIDEKICK_STORAGE_KEY_PREFIX = "sidekick-data";

/** Clé de stockage par utilisateur. Chaque user a ses propres données. */
export function getStorageKey(userId: string | null): string {
  return userId ? `${SIDEKICK_STORAGE_KEY_PREFIX}-${userId}` : `${SIDEKICK_STORAGE_KEY_PREFIX}-anon`;
}

// --- Tasks ---
export interface Todo {
  id: string;
  title: string;
  status: "todo" | "in_progress" | "done"; // remplace done: boolean
  todayFocus: boolean;
  description?: string;
  deadline?: string;
  sector?:
    | "Live"
    | "Phono"
    | "Admin"
    | "Marketing"
    | "Edition"
    | "Revenus"
    | "Projets"
    | "Autre";
  createdAt?: string;
  subtasks?: { id: string; title: string; done: boolean }[];
}

// --- Admin ---
export type AdminStatusType =
  | "auto_entrepreneur"
  | "association_1901"
  | "intermittent"
  | "artiste_auteur"
  | "sasu"
  // legacy (lus depuis la base puis normalisés côté client)
  | "sas_sasu"
  | "sarl_eurl";

export interface AdminStatus {
  id: string;
  nom: string;
  type: AdminStatusType;
  actif: boolean;
  dateDebut?: string;
  dateFin?: string;
  notes?: string;
  data?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface AdminStructure {
  id: string;
  name: string;
  [key: string]: unknown;
}
export interface AdminProcedure {
  id: string;
  label: string;
  status?: "a_faire" | "en_cours" | "termine";
  statutJuridiqueId?: string;
  organisme?: string;
  dateLimite?: string;
  recurrence?: "none" | "monthly" | "quarterly" | "semi_annual" | "annual" | "biannual";
  templateKey?: string;
  isAutoGenerated?: boolean;
  nextDueAt?: string;
  lastCompletedAt?: string;
  [key: string]: unknown;
}
export interface AdminDocument {
  id: string;
  title: string;
  [key: string]: unknown;
}

/** Dossier utilisateur (les dossiers par module sont prédéfinis, non stockés). */
export interface AdminDocumentFolder {
  id: string;
  name: string;
}
export interface AdminIntermittenceMission {
  id: string;
  label: string;
  [key: string]: unknown;
}

// --- Calendar ---
export interface CalendarEvent {
  id: string;
  title: string;
  start: string;
  end?: string;
  [key: string]: unknown;
}

// --- Contacts ---
export interface Contact {
  id: string;
  name: string;
  [key: string]: unknown;
}
export interface ProspectionItem {
  id: string;
  label: string;
  [key: string]: unknown;
}

// --- Dashboard ---
export interface Profile {
  displayName?: string;
  [key: string]: unknown;
}

// --- Edition ---

export type PersonRole = "author" | "composer" | "arranger" | "adapter";

/** Une personne impliquée dans l'œuvre (peut avoir plusieurs rôles) */
export interface Person {
  id: string;
  firstName: string;
  name: string;
  pseudonym: string;
  roles: PersonRole[];
}

/** Une part dans la distribution interne d'une catégorie */
export interface SplitEntry {
  personId: string; // référence à Person.id
  pct: number;      // 0–100, la somme de tous les SplitEntry d'une catégorie doit = 100
}

/** Clés SACEM — read-only, jamais modifiées par l'utilisateur */
export interface SacemRepartition {
  authors: number;    // % du total attribué aux auteurs
  composers: number;  // % du total attribué aux compositeurs
  publishers: number; // % du total attribué aux éditeurs
}

/** Un éditeur externe (société d'édition) — distinct des personnes physiques */
export interface EditionPublisher {
  id: string;
  name: string;
  coad: string; // Code international COAD
  pct: number;  // part dans la distribution éditeurs (sum = 100)
}

export interface Work {
  id: string;
  artistName: string;
  title: string;
  status: "in-progress" | "finalized" | "registered-sacem" | "accepted-sacem";

  persons: Person[];

  // Niveau 1 — clés SACEM (affichage uniquement)
  depRepartition: SacemRepartition;  // DEP par défaut : 33.33 / 33.33 / 33.33
  drmRepartition: SacemRepartition;  // DRM par défaut : 25 / 25 / 50

  // Niveau 2 — distribution interne par catégorie (sum = 100 chacune)
  splitsAuthors: SplitEntry[];
  splitsComposers: SplitEntry[];
  selfPublished: boolean;           // si true → l'artiste perçoit 100% de la part éditeurs
  externalPublishers: EditionPublisher[]; // éditeurs externes si selfPublished = false

  iswc: string;
  firstExploitationDate: string;
  genre: string;
  duration: string;
  files: { sheet?: string; lyrics?: string; audio?: string };
  exploitationTypes: ("streaming" | "live" | "sync" | "cover")[];
  firstBroadcaster: string;
  worldwideRights: boolean;
  territories: string[];
  notes: string;
  linkedTrackIds?: string[];
}

export interface Exploitant {
  id: string;
  company: string;
  project: "film" | "serie" | "pub" | "jeu-video" | "media" | "";
  date: string;
  status: "sent" | "discussing" | "accepted" | "refused" | "";
  notes: string;
}

export interface SyncData {
  workId: string;
  status: "not-ready" | "to-prepare" | "sync-ready" | "exploited";
  moods: string[];
  tempo: string;
  pitchShort: string;
  usageContext: string;
  themes: string[];
  privateLinks: string[];
  exploitants: Exploitant[];
}

// --- Incomes ---
export interface IncomeItem {
  id: string;
  label: string;
  amount?: number;
  [key: string]: unknown;
}

// --- Live ---
export interface TourDate {
  id: string;
  city: string;
  venue: string;
  date: string;
  status?: string;
  [key: string]: unknown;
}
export interface Rehearsal {
  id: string;
  label: string;
  date: string;
  location?: string;
  [key: string]: unknown;
}
export interface EquipmentItem {
  id: string;
  label: string;
  priority?: string;
  [key: string]: unknown;
}

// --- Marketing ---
export interface MailingItem {
  id: string;
  subject: string;
  [key: string]: unknown;
}
export interface MarketingEvent {
  id: string;
  title: string;
  date?: string;
  [key: string]: unknown;
}

// --- Projects ---
export interface ProjectMember {
  contactId: string | null;
  name: string;
  role: string;
}

export type ProjectStatus = "idea" | "in_progress" | "paused" | "done" | "archived";

export interface KeyDate {
  id: string;
  label: string;   // "Concert release", "Sortie clip"...
  type: string;    // "concert" | "sortie" | "clip" | "annonce" | ... (libre)
  date: string;    // ISO YYYY-MM-DD
}

export interface Project {
  id: string;
  title: string;
  description: string;
  status: ProjectStatus;
  cover: string;
  images: string[];
  sectors: ("phono" | "edition" | "live")[];
  members: ProjectMember[];
  linkedAlbums: string[];
  linkedTracks: string[];
  linkedSessions: string[];
  linkedWorks: string[];
  linkedTourDates: string[];
  linkedRehearsals: string[];
  linkedStatutIds: string[];   // → user_admin_statuses.id (phase 4)
  keyDates: KeyDate[];          // temps forts (phase 3)
  createdAt: string;
  updatedAt: string;
  notes: string;
  brainstorm: string;
  creationSeededSectors: CreationSector[];
  targetDate: string;
  pinned: boolean;
  pinnedOrder: number;
  manualMilestones: {
    editionWritingCompositionDone: boolean;
    liveConceptDone: boolean;
    liveSetlistDone: boolean;
    liveTeamDone: boolean;
  };
  objectives: ProjectObjective[];
  milestoneStates: Record<string, boolean>;
}

export type ProjectObjective =
  | "phono_single" | "phono_ep" | "phono_album"
  | "live_show" | "live_dj_set" | "live_tour"
  | "edition_composition" | "edition_lyrics" | "edition_sync";

// --- Project Creation ---
export type CreationStepStatus = "todo" | "doing" | "done";

export type CreationPhase = "creation" | "production" | "sortie";

export const CREATION_PHASE_ORDER: CreationPhase[] = ["creation", "production", "sortie"];

export const CREATION_PHASE_LABELS: Record<CreationPhase, string> = {
  creation: "Création",
  production: "Production",
  sortie: "Sortie",
};

export type CreationSector = "phono" | "edition" | "live" | "general";
export type CreationEntityType =
  | "" | "track" | "album" | "session" | "work" | "tour_date" | "rehearsal";

export interface CreationStepLink {
  label: string;
  url: string;
}

export interface CreationStep {
  id: string;
  projectId: string;
  phase: CreationPhase;
  sector: CreationSector;
  label: string;
  status: CreationStepStatus;
  orderIndex: number;
  targetDate: string | null;
  assignee: string;
  linkedEntityType: CreationEntityType;
  linkedEntityId: string;
  links: CreationStepLink[];
  taskId: string | null;
}

// --- Phono ---
export type PhonoRole =
  | "artiste_principal"
  | "artiste_secondaire"
  | "musicien_interprete"
  | "chanteur_interprete"
  | "directeur_musical"
  | "realisateur"
  | "compositeur"
  | "ingenieur_mixage"
  | "ingenieur_mastering"
  | "beatmaker"
  | "ingenieur_du_son";

/**
 * Un intervenant sur un titre.
 *
 * Historiquement stocké en chaîne concaténée `"Nom – Rôle"`, re-découpée sur
 * `" – "` à cinq endroits — dont le constructeur du payload de métadonnées.
 * Un nom contenant un tiret cassait silencieusement les crédits écrits dans le
 * fichier, sur des données qui alimentent des déclarations de droits.
 *
 * La colonne `guest_artists` est un `jsonb` : elle accepte les deux formes.
 * `normalizeTrackGuests` convertit à la lecture, l'écriture se fait toujours
 * au nouveau format.
 */
export interface TrackGuest {
  name: string;
  /** Libellé lisible, pas une clé `PhonoRole`. Ex. « Ingé Mixage ». */
  role: string;
}

/**
 * Fichier audio rattaché à une entité du catalogue.
 *
 * Partagé par `TrackVersion` et `Mix` : un DJ set est un fichier au même titre
 * qu'un master, et le lecteur, l'attachement et le calcul des peaks ne
 * connaissent que ces champs. Les dupliquer aurait fait diverger les deux.
 */
export interface AudioAttachment {
  /** Chemin dans le bucket `drive`. Absent = pas de fichier audio. */
  audioPath?: string;
  /** `upload` = fichier déposé depuis le catalogue, `drive` = fichier déjà rangé dans le Drive. */
  audioSource?: "upload" | "drive";
  /** Nom de fichier d'origine, affiché tel quel à l'artiste. */
  audioName?: string;
  durationMs?: number;
  sizeBytes?: number;
  /** ~400 valeurs entre 0 et 1, calculées dans le navigateur à l'ajout. */
  peaks?: number[];
}

export interface TrackVersion extends AudioAttachment {
  id: string;
  label: string;
  /**
   * ISRC propre à cette version. L'ISRC identifie un enregistrement, pas une
   * œuvre : radio edit, instrumental et live ont chacun le leur. Vide, la
   * version hérite de `Track.isrc` à l'affichage.
   */
  isrc?: string;
}

export interface Track {
  id: string;
  title: string;
  mainArtist: string;
  role: PhonoRole;
  /**
   * Tolère l'ancien format `"Nom – Rôle"` en lecture. Toujours écrit en
   * `TrackGuest[]`. Utiliser `normalizeTrackGuests` avant tout usage.
   */
  guestArtists: Array<string | TrackGuest>;
  isrc: string;
  releaseDate: string;
  selfProduced: boolean;
  label?: string;
  editor?: string;
  versions: TrackVersion[];
  genre?: string;
  distribution?: string;
  notes: string;
  status?: ReleaseStatus;
  cover?: string;
  linkedWorkId?: string;
  [key: string]: unknown;
}

export type AlbumType = "album" | "ep" | "single";

export type ReleaseStatus =
  | "en_production"
  | "mixe"
  | "masterise"
  | "publie";

export interface AlbumGuest {
  id: string;
  name: string;
  role: PhonoRole;
}

export interface Album {
  id: string;
  title: string;
  type: AlbumType;
  status: ReleaseStatus;
  artist: string;
  releaseDate: string;
  upcEan: string;
  trackIds: string[];
  /**
   * Versions retenues pour chaque titre de l'album, dans l'ordre d'écoute.
   *
   * Un album porte couramment deux déclinaisons d'un même titre (Master et
   * Radio Edit) : d'où une liste par titre, pas un identifiant unique. Une
   * clé absente signifie « album d'avant cette donnée » et déclenche le repli
   * historique (première version pourvue d'un fichier) ; une liste vide est au
   * contraire un choix explicite de n'en inclure aucune. Toujours lu par
   * `albumTrackVersions`, jamais à la main.
   */
  trackVersions?: Record<string, string[]>;
  label?: string;
  genre?: string;
  editor?: string;
  distribution?: string;
  notes: string;
  cover?: string;
  guests?: AlbumGuest[];
  [key: string]: unknown;
}
export interface Session {
  id: string;
  title: string;
  date?: string;
  [key: string]: unknown;
}

export interface MixTracklistItem {
  id: string;
  artist: string;
  /**
   * Titre du morceau joué, séparé de l'artiste.
   *
   * Les tracklists saisies avant cette séparation portent « Artiste – Titre »
   * dans `artist` seul : `normalizeMix` les redécoupe à la lecture.
   */
  title: string;
  label: string;
  /** Timecode `M:SS` ou `H:MM:SS`. */
  time: string;
}

/**
 * Longs formats non phonographiques : DJ set, live set, mix, émission.
 *
 * Ils n'ont ni ISRC ni version ni distributeur. Leur valeur juridique tient à
 * la tracklist, qui détermine la répartition des droits vers les ayants droit
 * des titres joués — c'est le format exigé par Mixcloud, Resident Advisor et
 * la SACEM.
 */
/**
 * `mix` et `podcast` ne sont plus proposés : le catalogue s'en tient à « Live »
 * et « DJ set ». Ils restent dans le type pour les mixes enregistrés avant,
 * que `normalizeMix` ramène sur `dj_set` (voir `MIX_FORMATS`).
 */
export type MixFormat = "dj_set" | "live_set" | "mix" | "podcast";

export interface Mix extends AudioAttachment {
  id: string;
  title: string;
  artists: string;
  publishedOn: string;
  format: MixFormat;
  /** Captation vidéo. Orthogonal au format : un live set peut être filmé. */
  isVideo: boolean;
  status: ReleaseStatus;
  releaseDate: string;
  tracklist: MixTracklistItem[];
  cover?: string;
  [key: string]: unknown;
}

// --- Store global ---
export interface SidekickData {
  tasks: Todo[];
  admin: {
    statuses: AdminStatus[];
    structures: AdminStructure[];
    procedures: AdminProcedure[];
    documents: AdminDocument[];
    documentFolders: AdminDocumentFolder[];
    storageUsedBytes: number;
    intermittenceMissions: AdminIntermittenceMission[];
  };
  calendar: {
    events: CalendarEvent[];
  };
  contacts: {
    contacts: Contact[];
    prospection: ProspectionItem[];
  };
  dashboard: {
    profile: Profile;
  };
  edition: {
    works: Work[];
    sync: Record<string, SyncData>;
  };
  incomes: {
    royalties: IncomeItem[];
    invoices: IncomeItem[];
    copyright: IncomeItem[];
  };
  live: {
    tourDates: TourDate[];
    rehearsals: Rehearsal[];
    equipment: EquipmentItem[];
  };
  marketing: {
    mailing: MailingItem[];
    events: MarketingEvent[];
    editorialPlatforms: string[];
    editorialContentTypes: string[];
  };
  phono: {
    albums: Album[];
    tracks: Track[];
    sessions: Session[];
    mixes: Mix[];
  };
  projects: {
    projects: Project[];
  };
  preferences: {
    enabledModules: {
      live: boolean;
      phono: boolean;
      admin: boolean;
      marketing: boolean;
      edition: boolean;
      revenus: boolean;
      projects: boolean;
    };
    /** Pied de facture réutilisé pour les nouvelles factures (après 1ère saisie / enregistrement). */
    invoiceFooterNote?: string;
    /** Modèle visuel des PDF de facture (couleur d'accent, police, logo). */
    invoiceTemplate?: InvoiceTemplate;
  };
}

/** Préférences de mise en forme du PDF de facture. */
export interface InvoiceTemplate {
  /** Couleur d'accent (titres, total TTC, filets). Hex. */
  accentColor: string;
  /** Clé de la police (voir INVOICE_FONTS dans le module incomes). */
  fontFamily: string;
  /** Termes et conditions affichés en bas de chaque facture. */
  termsAndConditions?: string;
  /**
   * Mise en page du PDF de fiche technique (module Live). Rangée ici pour que
   * couleur, police et logo restent communs à tous les documents de l'artiste,
   * sans colonne de plus en base (`user_preferences.invoice_template`, jsonb).
   */
  technicalLayout?: TechnicalLayout;
}

/** Mises en page proposées pour la fiche technique. Absent = « classic ». */
export type TechnicalLayout = "classic" | "poster" | "compact";

export const DEFAULT_TERMS_AND_CONDITIONS =
  `En cas de retard de paiement, seront exigibles, conformément au code de commerce, une indemnité calculée sur la base de trois fois le taux de l'intérêt légal en vigueur ainsi qu'une indemnité forfaitaire pour frais de recouvrement de 40€.\nPas d'escompte en cas de paiement anticipé.`;

export const DEFAULT_INVOICE_TEMPLATE: InvoiceTemplate = {
  accentColor: "#101010",
  fontFamily: "Inter",
  termsAndConditions: DEFAULT_TERMS_AND_CONDITIONS,
};

export const DEFAULT_SIDEKICK_DATA: SidekickData = {
  tasks: [],
  admin: {
    statuses: [],
    structures: [],
    procedures: [],
    documents: [],
    documentFolders: [],
    storageUsedBytes: 0,
    intermittenceMissions: []
  },
  calendar: {
    events: []
  },
  contacts: {
    contacts: [],
    prospection: []
  },
  dashboard: {
    profile: {}
  },
  edition: {
    works: [],
    sync: {}
  },
  incomes: {
    royalties: [],
    invoices: [],
    copyright: [],
  },
  live: {
    tourDates: [],
    rehearsals: [],
    equipment: []
  },
  marketing: {
    mailing: [],
    events: [],
    editorialPlatforms: [],
    editorialContentTypes: []
  },
  phono: {
    albums: [],
    tracks: [],
    sessions: [],
    mixes: []
  },
  projects: {
    projects: [],
  },
  preferences: {
    enabledModules: {
      live: true,
      phono: true,
      admin: true,
      marketing: true,
      edition: true,
      revenus: true,
      projects: true,
    },
  }
};

/**
 * Fusionne des données partielles (ex. ancien localStorage) avec les défauts.
 */
export function mergeWithDefaults(
  partial: Partial<SidekickData> | null
): SidekickData {
  if (!partial || typeof partial !== "object") return DEFAULT_SIDEKICK_DATA;
  return {
    ...DEFAULT_SIDEKICK_DATA,
    ...partial,
    tasks: Array.isArray(partial.tasks)
      ? partial.tasks.map((t: Todo & { done?: boolean }) => ({
          ...t,
          // Migration: ancien format done: boolean → status
          status: t.status ?? (t.done ? "done" : "todo"),
          todayFocus: t.todayFocus ?? false,
        }))
      : DEFAULT_SIDEKICK_DATA.tasks,
    admin: {
      ...DEFAULT_SIDEKICK_DATA.admin,
      ...partial.admin,
      statuses: Array.isArray(partial.admin?.statuses) ? partial.admin.statuses : DEFAULT_SIDEKICK_DATA.admin.statuses,
      documents: Array.isArray(partial.admin?.documents) ? partial.admin.documents : DEFAULT_SIDEKICK_DATA.admin.documents,
      documentFolders: Array.isArray(partial.admin?.documentFolders) ? partial.admin.documentFolders : DEFAULT_SIDEKICK_DATA.admin.documentFolders,
      storageUsedBytes: typeof partial.admin?.storageUsedBytes === "number" ? partial.admin.storageUsedBytes : DEFAULT_SIDEKICK_DATA.admin.storageUsedBytes
    },
    calendar: { ...DEFAULT_SIDEKICK_DATA.calendar, ...partial.calendar },
    contacts: { ...DEFAULT_SIDEKICK_DATA.contacts, ...partial.contacts },
    dashboard: { ...DEFAULT_SIDEKICK_DATA.dashboard, ...partial.dashboard },
    edition: {
      ...DEFAULT_SIDEKICK_DATA.edition,
      ...partial.edition,
      works: Array.isArray(partial.edition?.works)
        ? partial.edition.works
        : DEFAULT_SIDEKICK_DATA.edition.works,
      sync:
        partial.edition?.sync &&
        typeof partial.edition.sync === "object" &&
        !Array.isArray(partial.edition.sync)
          ? (partial.edition.sync as Record<string, SyncData>)
          : DEFAULT_SIDEKICK_DATA.edition.sync,
    },
    incomes: { ...DEFAULT_SIDEKICK_DATA.incomes, ...partial.incomes },
    live: { ...DEFAULT_SIDEKICK_DATA.live, ...partial.live },
    marketing: { ...DEFAULT_SIDEKICK_DATA.marketing, ...partial.marketing },
    phono: { ...DEFAULT_SIDEKICK_DATA.phono, ...partial.phono },
    projects: {
      ...DEFAULT_SIDEKICK_DATA.projects,
      ...partial.projects,
      projects: Array.isArray(partial.projects?.projects)
        ? partial.projects.projects
        : DEFAULT_SIDEKICK_DATA.projects.projects,
    },
    preferences: (() => {
      const prefRest = { ...(partial.preferences ?? {}) };
      delete (prefRest as { aiTaskInstructions?: unknown }).aiTaskInstructions;
      return {
        ...DEFAULT_SIDEKICK_DATA.preferences,
        ...prefRest,
        enabledModules: {
          ...DEFAULT_SIDEKICK_DATA.preferences.enabledModules,
          ...(partial.preferences?.enabledModules ?? {}),
        },
      };
    })(),
  };
}
