"use client";

import { useMemo, useState } from "react";
import Image from "next/image";
import { useRouter } from "next/navigation";
import { ArrowLeft, BookOpen, Check, ChevronDown, ImagePlus, Link2, Mic2, Music2, Plus, Sparkles, X } from "lucide-react";
import { toast } from "sonner";
import { useProjectsData } from "@/hooks/useProjectsData";
import { usePhonoData } from "@/hooks/usePhonoData";
import { useEditionData } from "@/hooks/useEditionData";
import { useLiveData } from "@/hooks/useLiveData";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { DatePicker } from "@/components/ui/date-picker";
import { Checkbox } from "@/components/ui/checkbox";
import { cn, focusRing } from "@/lib/utils";
import type { AlbumType, ProjectObjective, ProjectStatus } from "@/lib/sidekick-store";

type DraftRelease = { id: string; title: string; artist: string; type: AlbumType; releaseDate: string; cover: string };
type DraftWork = { id: string; title: string; artistName: string };

const OBJECTIVES: Record<"phono" | "live" | "edition", Array<{ id: ProjectObjective; label: string; hint: string }>> = {
  phono: [
    { id: "phono_single", label: "Single", hint: "Préparer et sortir un morceau seul." },
    { id: "phono_ep", label: "EP", hint: "Regrouper plusieurs titres dans un format court." },
    { id: "phono_album", label: "Album", hint: "Construire une sortie longue et sa tracklist." },
  ],
  live: [
    { id: "live_show", label: "Créer un spectacle / concert", hint: "Concept, set, équipe, matériel, répétitions et fiche technique." },
    { id: "live_dj_set", label: "Créer un DJ set", hint: "Ambiance, sélection musicale, structure, matériel et fiche technique." },
    { id: "live_tour", label: "Organiser une tournée", hint: "Prospection, dates, confirmations, cachets et logistique — même si ton set est déjà prêt." },
  ],
  edition: [
    { id: "edition_composition", label: "Composition", hint: "Suivre la création musicale de tes œuvres." },
    { id: "edition_lyrics", label: "Écriture de textes", hint: "Suivre l’écriture et la finalisation de tes paroles." },
    { id: "edition_sync", label: "Synchronisation à l’image", hint: "Préparer une œuvre, son pitch et ses supports d’écoute pour l’image." },
  ],
};

const SECTORS = [
  { id: "phono" as const, icon: Music2, title: "Phono", kicker: "Enregistrements et sorties", description: "Prépare les morceaux que le public écoutera : single, EP ou album, de la production jusqu’à la sortie." },
  { id: "live" as const, icon: Mic2, title: "Live", kicker: "Spectacles et concerts", description: "Construis ce que tu joueras sur scène, prépare ton matériel et organise tes futures dates ou ta tournée." },
  { id: "edition" as const, icon: BookOpen, title: "Édition", kicker: "Œuvres et droits d’auteur", description: "Suis la composition et les textes de tes chansons, puis prépare leur dépôt ou leur utilisation à l’image." },
];

function SearchList({ title, items, selected, onToggle }: { title: string; items: Array<{ id: string; label: string; detail?: string }>; selected: string[]; onToggle: (id: string) => void }) {
  const [query, setQuery] = useState("");
  const visible = items.filter((item) => `${item.label} ${item.detail ?? ""}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="rounded-lg border border-white/[.08] bg-black/10 p-3"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-white/35">{title}</p>{items.length ? <><Input className="mt-3 h-8 text-xs" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Rechercher…" /><div className="mt-2 max-h-44 space-y-1 overflow-y-auto">{visible.map((item) => <label key={item.id} className="flex cursor-pointer items-center gap-3 rounded-md px-2 py-2 hover:bg-white/[.04]"><Checkbox checked={selected.includes(item.id)} onCheckedChange={() => onToggle(item.id)} /><span className="min-w-0 flex-1"><span className="block truncate text-xs text-white/75">{item.label}</span>{item.detail && <span className="block truncate text-[10px] text-white/30">{item.detail}</span>}</span></label>)}</div></> : <p className="mt-2 text-xs text-white/30">Aucun élément existant.</p>}</div>;
}

export function ProjectCreatePage() {
  const router = useRouter(); const { createProjectBundle } = useProjectsData(); const phono = usePhonoData(); const edition = useEditionData(); const live = useLiveData();
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [targetDate, setTargetDate] = useState(""); const [cover, setCover] = useState("");
  const [sectors, setSectors] = useState<Array<"phono" | "live" | "edition">>([]); const [objectives, setObjectives] = useState<ProjectObjective[]>([]); const [status, setStatus] = useState<ProjectStatus>("in_progress");
  const [linkedAlbums, setLinkedAlbums] = useState<string[]>([]); const [linkedTracks, setLinkedTracks] = useState<string[]>([]); const [linkedWorks, setLinkedWorks] = useState<string[]>([]); const [linkedDates, setLinkedDates] = useState<string[]>([]);
  const [newReleases, setNewReleases] = useState<DraftRelease[]>([]); const [newWorks, setNewWorks] = useState<DraftWork[]>([]); const [saving, setSaving] = useState(false);
  const toggle = <T,>(items: T[], item: T, setter: (next: T[]) => void) => setter(items.includes(item) ? items.filter((value) => value !== item) : [...items, item]);
  const toggleSector = (sector: "phono" | "live" | "edition") => { if (sectors.includes(sector)) { setSectors(sectors.filter((item) => item !== sector)); setObjectives(objectives.filter((item) => !item.startsWith(`${sector}_`))); } else setSectors([...sectors, sector]); };
  const selectedExisting = linkedAlbums.length + linkedTracks.length + linkedWorks.length + linkedDates.length;
  const connectionCount = selectedExisting + newReleases.length + newWorks.length;
  const suggestedCover = useMemo(() => cover || newReleases.find((item) => item.cover)?.cover || phono.albums.find((item) => linkedAlbums.includes(item.id) && item.cover)?.cover || phono.tracks.find((item) => linkedTracks.includes(item.id) && item.cover)?.cover || "", [cover, newReleases, phono.albums, phono.tracks, linkedAlbums, linkedTracks]);
  const handleImage = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => setCover(String(reader.result ?? "")); reader.readAsDataURL(file); };
  const addRelease = (type: AlbumType) => setNewReleases((prev) => [...prev, { id: `a-${crypto.randomUUID()}`, title: "", artist: "", type, releaseDate: "", cover: "" }]);
  const addWork = () => setNewWorks((prev) => [...prev, { id: `w-${crypto.randomUUID()}`, title: "", artistName: "" }]);
  const canSave = title.trim() && sectors.length && objectives.length && newReleases.every((item) => item.title.trim()) && newWorks.every((item) => item.title.trim());
  const save = async () => { if (!canSave || saving) return; setSaving(true); try { const id = await createProjectBundle({ id: crypto.randomUUID(), title: title.trim(), description: description.trim(), cover: suggestedCover, targetDate, status, sectors, objectives, milestoneStates: {}, linkedAlbumIds: linkedAlbums, linkedTrackIds: linkedTracks, linkedWorkIds: linkedWorks, linkedTourDateIds: linkedDates, newAlbums: newReleases, newWorks }); toast.success("Projet créé et modules reliés."); router.push(`/projects/${id}`); } catch (error) { toast.error(error instanceof Error ? error.message : "Impossible de créer le projet."); setSaving(false); } };

  return <div className="max-w-6xl pb-12"><button onClick={() => router.push("/projects")} className={cn("flex items-center gap-1.5 rounded-sm text-xs text-white/40 hover:text-white", focusRing)}><ArrowLeft size={13} /> Projets</button><div className="mt-6 grid gap-8 lg:grid-cols-[minmax(0,1fr)_300px]">
    <main className="min-w-0 space-y-5"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-[#F0FF00]">Nouveau projet</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Donne un cap à ce que tu crées.</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-white/50">Choisis ce que ce projet réunit. SIDEKICK connectera les bons modules et construira automatiquement son suivi.</p></div>
      <section className="rounded-xl border border-white/[.08] bg-[rgba(44,44,46,.5)] p-5"><h2 className="text-[11px] font-semibold uppercase tracking-[.12em] text-[#F0FF00]">1 · L’essentiel</h2><p className="mt-1 text-xs text-white/45">Seul le nom est obligatoire. Tout le reste pourra évoluer.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="project-name">Nom du projet *</Label><Input id="project-name" value={title} onChange={(e) => setTitle(e.target.value)} placeholder="EP Horizon, tournée d’été…" /></div><div className="space-y-2"><Label>Date cible <span className="text-white/30">· facultative</span></Label><DatePicker value={targetDate} onChange={setTargetDate} placeholder="Ajouter une date cible" /></div></div><div className="mt-4 space-y-2"><Label>Description courte <span className="text-white/30">· facultative</span></Label><Textarea value={description} onChange={(e) => setDescription(e.target.value)} placeholder="L’objectif, l’univers ou le résultat attendu…" rows={3} /></div><div className="mt-4"><Label>Image <span className="text-white/30">· facultative</span></Label><div className="mt-2 flex items-center gap-3">{suggestedCover && <div className="relative h-16 w-16 overflow-hidden rounded-lg"><Image src={suggestedCover} alt="" fill unoptimized className="object-cover" /></div>}<label className="flex cursor-pointer items-center gap-2 rounded-md border border-dashed border-white/15 px-3 py-2 text-xs text-white/45 hover:border-white/30 hover:text-white"><ImagePlus size={14} /> Choisir une image<input type="file" accept="image/*" className="hidden" onChange={(e) => handleImage(e.target.files?.[0])} /></label>{cover && <button onClick={() => setCover("")} aria-label="Retirer l’image"><X size={14} className="text-white/35" /></button>}</div></div></section>
      <section className="rounded-xl border border-white/[.08] bg-[rgba(44,44,46,.5)] p-5"><h2 className="text-[11px] font-semibold uppercase tracking-[.12em] text-[#F0FF00]">2 · Ce que réunit ton projet</h2><p className="mt-1 text-xs text-white/45">Active un ou plusieurs secteurs. Aucun vocabulaire métier nécessaire.</p><div className="mt-5 space-y-3">{SECTORS.map(({ id, icon: Icon, title: sectorTitle, kicker, description: sectorDescription }) => { const active = sectors.includes(id); return <div key={id} className={cn("overflow-hidden rounded-xl border transition-colors", active ? "border-[#F0FF00]/35 bg-[#F0FF00]/[.025]" : "border-white/[.08]")}><button type="button" onClick={() => toggleSector(id)} aria-expanded={active} className={cn("flex w-full items-start gap-4 p-4 text-left", focusRing)}><span className={cn("flex h-10 w-10 shrink-0 items-center justify-center rounded-lg", active ? "bg-[#F0FF00] text-black" : "bg-white/[.05] text-white/45")}><Icon size={18} /></span><span className="flex-1"><span className="block text-sm font-semibold">{sectorTitle} <span className="ml-1 font-normal text-white/35">— {kicker}</span></span><span className="mt-1 block max-w-2xl text-xs leading-relaxed text-white/45">{sectorDescription}</span></span><ChevronDown size={16} className={cn("mt-2 text-white/30 transition-transform", active && "rotate-180")} /></button>{active && <div className="border-t border-white/[.07] px-4 pb-4 pt-3"><p className="mb-2 text-[10px] font-semibold uppercase tracking-[.12em] text-white/30">Que veux-tu faire ?</p><div className="grid gap-2 sm:grid-cols-3">{OBJECTIVES[id].map((objective) => { const chosen = objectives.includes(objective.id); return <button key={objective.id} type="button" onClick={() => toggle(objectives, objective.id, setObjectives)} aria-pressed={chosen} className={cn("rounded-lg border p-3 text-left", chosen ? "border-[#F0FF00]/40 bg-[#F0FF00]/[.06]" : "border-white/[.08] hover:border-white/20")}><span className="flex items-center justify-between text-xs font-semibold">{objective.label}{chosen && <Check size={13} className="text-[#F0FF00]" />}</span><span className="mt-1 block text-[10px] leading-relaxed text-white/35">{objective.hint}</span></button>; })}</div></div>}</div>; })}</div></section>
      {objectives.length > 0 && <section className="rounded-xl border border-white/[.08] bg-[rgba(44,44,46,.5)] p-5"><h2 className="text-[11px] font-semibold uppercase tracking-[.12em] text-[#F0FF00]">3 · Relie ce qui existe déjà</h2><p className="mt-1 text-xs text-white/45">Facultatif : commence vide ou donne tout de suite du contexte à ton projet.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{objectives.some((item) => item.startsWith("phono_")) && <><SearchList title="Albums, EP et singles" items={phono.albums.map((item) => ({ id: item.id, label: item.title, detail: item.artist }))} selected={linkedAlbums} onToggle={(id) => toggle(linkedAlbums, id, setLinkedAlbums)} /><SearchList title="Titres" items={phono.tracks.map((item) => ({ id: item.id, label: item.title, detail: item.mainArtist }))} selected={linkedTracks} onToggle={(id) => toggle(linkedTracks, id, setLinkedTracks)} /></>}{objectives.some((item) => item.startsWith("edition_")) && <SearchList title="Œuvres" items={edition.works.map((item) => ({ id: item.id, label: item.title, detail: item.artistName }))} selected={linkedWorks} onToggle={(id) => toggle(linkedWorks, id, setLinkedWorks)} />}{objectives.includes("live_tour") && <SearchList title="Dates live" items={live.tourDates.map((item) => ({ id: String(item.id), label: item.venue || item.city, detail: `${item.city} · ${item.date}` }))} selected={linkedDates} onToggle={(id) => toggle(linkedDates, id, setLinkedDates)} />}</div>
        {objectives.some((item) => item.startsWith("phono_")) && <div className="mt-5"><p className="text-xs font-medium text-white/65">Ou crée une sortie maintenant</p><div className="mt-2 flex flex-wrap gap-2">{(["single", "ep", "album"] as AlbumType[]).filter((type) => objectives.includes(`phono_${type}` as ProjectObjective)).map((type) => <Button key={type} variant="outline" size="sm" onClick={() => addRelease(type)}><Plus size={13} /> {type === "ep" ? "EP" : type === "album" ? "Album" : "Single"}</Button>)}</div>{newReleases.map((item, index) => <div key={item.id} className="mt-3 grid gap-3 rounded-lg border border-white/[.08] p-3 sm:grid-cols-[1fr_1fr_auto]"><Input value={item.title} onChange={(e) => setNewReleases((prev) => prev.map((value, i) => i === index ? { ...value, title: e.target.value } : value))} placeholder={`Nom du ${item.type}`} /><Input value={item.artist} onChange={(e) => setNewReleases((prev) => prev.map((value, i) => i === index ? { ...value, artist: e.target.value } : value))} placeholder="Artiste · facultatif" /><button onClick={() => setNewReleases((prev) => prev.filter((_, i) => i !== index))} aria-label="Retirer"><X size={14} className="text-white/35" /></button></div>)}</div>}
        {objectives.some((item) => item.startsWith("edition_")) && <div className="mt-5"><Button variant="outline" size="sm" onClick={addWork}><Plus size={13} /> Créer une œuvre</Button>{newWorks.map((item, index) => <div key={item.id} className="mt-3 grid gap-3 rounded-lg border border-white/[.08] p-3 sm:grid-cols-[1fr_1fr_auto]"><Input value={item.title} onChange={(e) => setNewWorks((prev) => prev.map((value, i) => i === index ? { ...value, title: e.target.value } : value))} placeholder="Titre de l’œuvre" /><Input value={item.artistName} onChange={(e) => setNewWorks((prev) => prev.map((value, i) => i === index ? { ...value, artistName: e.target.value } : value))} placeholder="Artiste · facultatif" /><button onClick={() => setNewWorks((prev) => prev.filter((_, i) => i !== index))} aria-label="Retirer"><X size={14} className="text-white/35" /></button></div>)}</div>}
        <p className="mt-4 flex items-center gap-2 text-[11px] text-white/35"><Link2 size={12} className="text-[#F0FF00]/60" /> Ces éléments alimenteront automatiquement la progression et les échéances du projet.</p></section>}
      {objectives.length > 0 && <section className="rounded-xl border border-white/[.08] bg-[rgba(44,44,46,.5)] p-5"><h2 className="text-[11px] font-semibold uppercase tracking-[.12em] text-[#F0FF00]">4 · Lance ton projet</h2><p className="mt-1 text-xs text-white/45">Tu pourras modifier son périmètre depuis le cockpit.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{([{ value: "in_progress", label: "En cours", hint: "Je commence à travailler dessus maintenant." }, { value: "idea", label: "Idée", hint: "Je le garde de côté pour plus tard." }] as const).map((option) => <button key={option.value} onClick={() => setStatus(option.value)} className={cn("rounded-lg border p-3 text-left", status === option.value ? "border-[#F0FF00]/40 bg-[#F0FF00]/[.06]" : "border-white/[.08]")}><span className="text-xs font-semibold">{option.label}</span><span className="mt-1 block text-[10px] text-white/35">{option.hint}</span></button>)}</div></section>}
    </main>
    <aside className="lg:sticky lg:top-6 lg:self-start"><div className="overflow-hidden rounded-xl border border-white/[.09] bg-[#171717]"><div className="relative h-36 bg-gradient-to-br from-[#252536] to-[#121218]">{suggestedCover ? <Image src={suggestedCover} alt="" fill unoptimized className="object-cover" /> : <div className="flex h-full items-center justify-center"><Sparkles size={24} className="text-white/10" /></div>}</div><div className="p-4"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#F0FF00]/60">Aperçu du cockpit</p><h2 className="mt-2 truncate text-lg font-semibold">{title || "Ton nouveau projet"}</h2><p className="mt-1 line-clamp-2 min-h-8 text-[11px] leading-relaxed text-white/35">{description || "Son objectif apparaîtra ici."}</p><div className="mt-4 space-y-3 border-t border-white/[.07] pt-4"><div className="flex justify-between text-xs"><span className="text-white/35">Secteurs</span><span>{sectors.length || "—"}</span></div><div className="flex justify-between text-xs"><span className="text-white/35">Objectifs</span><span>{objectives.length || "—"}</span></div><div className="flex justify-between text-xs"><span className="text-white/35">Éléments reliés</span><span>{connectionCount || "—"}</span></div><div><div className="flex justify-between text-[10px] text-white/35"><span>Progression initiale</span><span>{connectionCount ? "Calculée après création" : "À démarrer"}</span></div><div className="mt-2 h-1.5 rounded-full bg-white/[.06]" /></div></div><Button className="mt-5 w-full" disabled={!canSave || saving} onClick={save}>{saving ? "Création…" : "Créer et ouvrir le projet"}</Button>{!sectors.length && title && <p className="mt-2 text-center text-[10px] text-amber-300/60">Active au moins un secteur.</p>}</div></div></aside>
  </div></div>;
}
