import type { AdminProcedure } from "@/lib/sidekick-store";
import { frToIso, isValidDateFr } from "@/lib/date-format";
import { getCanonicalNafCode } from "@/modules/admin/lib/naf-codes";
import type { ProcedureRecurrence } from "@/modules/admin/data/procedure-templates";

export type AeDeclarationCadence = "monthly" | "quarterly";

export type AeMicroHeuristic = "bic_vente" | "services" | "bnc" | "liberal";

export type AeSocialFiscalMode = "liberatoire" | "micro_social";

export interface AeDemarchesPersisted {
  declarationCadence: AeDeclarationCadence;
  /** CA année civile en cours (€), pour affichage / logique CFE */
  cfeCurrentYearCaEuros?: string;
  cfeMarkedExempt?: boolean;
  socialFiscalMode: AeSocialFiscalMode;
}

const AE_TEMPLATE_KEYS = ["ae_declaration_ca", "ae_cfe", "ae_versement_liberatoire"] as const;
export type AeManagedTemplateKey = (typeof AE_TEMPLATE_KEYS)[number];

export const DEFAULT_AE_DEMARCHES: AeDemarchesPersisted = {
  declarationCadence: "quarterly",
  socialFiscalMode: "micro_social",
};

export function parseCreationYearFromFrDate(frDate: string): number | null {
  const t = frDate.trim();
  if (!t || !isValidDateFr(t)) return null;
  const iso = frToIso(t);
  const y = parseInt(iso.slice(0, 4), 10);
  return Number.isFinite(y) ? y : null;
}

export function inferAeMicroHeuristicFromApe(ape: string): AeMicroHeuristic {
  const canonical = getCanonicalNafCode(ape) ?? ape;
  const m = canonical.trim().match(/^(\d{2})/);
  const div = m ? parseInt(m[1], 10) : NaN;
  if (Number.isNaN(div)) return "services";
  if (div >= 45 && div <= 47) return "bic_vente";
  if (div >= 86 && div <= 88) return "liberal";
  if (div === 66 || div === 69) return "bnc";
  return "services";
}

export function microHeuristicLabel(h: AeMicroHeuristic): string {
  switch (h) {
    case "bic_vente":
      return "BIC — vente de marchandises / restauration";
    case "services":
      return "BIC — prestations de services";
    case "bnc":
      return "BNC";
    case "liberal":
      return "Professions libérales réglementées";
  }
}

/** Ordres de grandeur indicatifs — à confirmer selon la réglementation en vigueur. */
export function microPlafondHintEuros(h: AeMicroHeuristic): number {
  switch (h) {
    case "bic_vente":
      return 188_700;
    default:
      return 77_700;
  }
}

export function defaultSocialFiscalFromHeuristic(h: AeMicroHeuristic): AeSocialFiscalMode {
  if (h === "liberal" || h === "bnc") return "micro_social";
  return "liberatoire";
}

/** Seul le choix explicite « exonéré » supprime la démarche CFE (CA et 1re année ne la bloquent plus). */
export function shouldSkipCfeProcedure(cfeMarkedExempt: boolean): boolean {
  return cfeMarkedExempt === true;
}

/** Première année civile = année de la date de création : CFE créée, échéance repoussée en N+1 (indicatif mi-décembre). */
export function isCfeFirstCalendarYearOfActivity(
  creationYear: number | null,
  calendarYear: number
): boolean {
  return creationYear !== null && creationYear === calendarYear;
}

/** Date limite indicative pour la première CFE après l’exonération de l’année de création (15 déc. N+1). */
export function cfeFirstDueAfterCreationYearIso(calendarYear: number): string {
  const d = new Date(calendarYear + 1, 11, 15);
  d.setHours(12, 0, 0, 0);
  return d.toISOString().slice(0, 10);
}

export function isSecondCalendarYearAfterCreation(
  creationYear: number | null,
  calendarYear: number
): boolean {
  if (creationYear === null) return false;
  return calendarYear - creationYear === 2;
}

function procedureFromTemplate(args: {
  statusId: string;
  templateKey: AeManagedTemplateKey;
  label: string;
  organisme?: string;
  recurrence: ProcedureRecurrence;
  defaultDueInDays: number;
  /** Si défini, remplace le calcul « aujourd’hui + defaultDueInDays ». */
  dateLimiteIso?: string;
}): AdminProcedure {
  let dateLimite: string;
  if (args.dateLimiteIso) {
    dateLimite = args.dateLimiteIso;
  } else {
    const today = new Date();
    const due = new Date(today);
    due.setDate(due.getDate() + args.defaultDueInDays);
    dateLimite = due.toISOString().slice(0, 10);
  }
  return {
    id: crypto.randomUUID(),
    label: args.label,
    status: "a_faire",
    statutJuridiqueId: args.statusId,
    organisme: args.organisme,
    recurrence: args.recurrence,
    templateKey: args.templateKey,
    isAutoGenerated: true,
    dateLimite,
  };
}

function declarationRecurrence(cadence: AeDeclarationCadence): ProcedureRecurrence {
  return cadence === "monthly" ? "monthly" : "quarterly";
}

export function buildAeAutoProcedures(args: {
  statusId: string;
  dem: AeDemarchesPersisted;
  creationYear: number | null;
  calendarYear: number;
}): AdminProcedure[] {
  const { statusId, dem, creationYear, calendarYear } = args;
  const rec = declarationRecurrence(dem.declarationCadence);
  const cadenceLabel = dem.declarationCadence === "monthly" ? "mensuel" : "trimestriel";
  const list: AdminProcedure[] = [];

  list.push(
    procedureFromTemplate({
      statusId,
      templateKey: "ae_declaration_ca",
      label: `Déclaration de chiffre d'affaires (${cadenceLabel})`,
      organisme: "URSSAF",
      recurrence: rec,
      defaultDueInDays: dem.declarationCadence === "monthly" ? 30 : 45,
    })
  );

  if (!shouldSkipCfeProcedure(Boolean(dem.cfeMarkedExempt))) {
    const firstYear = isCfeFirstCalendarYearOfActivity(creationYear, calendarYear);
    list.push(
      procedureFromTemplate({
        statusId,
        templateKey: "ae_cfe",
        label: firstYear
          ? "Vérifier et payer la CFE (1re échéance après l’année de création)"
          : "Vérifier et payer la CFE",
        organisme: "Impôts",
        recurrence: "annual",
        defaultDueInDays: 180,
        dateLimiteIso: firstYear ? cfeFirstDueAfterCreationYearIso(calendarYear) : undefined,
      })
    );
  }

  if (dem.socialFiscalMode === "liberatoire") {
    list.push(
      procedureFromTemplate({
        statusId,
        templateKey: "ae_versement_liberatoire",
        label: `Versement libératoire d'impôt sur le revenu (${cadenceLabel}, avec l'URSSAF)`,
        organisme: "Impôts / URSSAF",
        recurrence: rec,
        defaultDueInDays: dem.declarationCadence === "monthly" ? 30 : 45,
      })
    );
  }

  return list;
}

export function isAeManagedAutoProcedure(
  p: AdminProcedure,
  statusId: string
): p is AdminProcedure & { templateKey: AeManagedTemplateKey } {
  if (p.statutJuridiqueId !== statusId) return false;
  if (!p.isAutoGenerated) return false;
  const tk = p.templateKey as string | undefined;
  return Boolean(tk && (AE_TEMPLATE_KEYS as readonly string[]).includes(tk));
}

/** Synchronise les démarches auto AE : conserve id, statut et échéances quand la clé template existe déjà. */
export function mergeSyncedAeAutoProcedures(
  prev: AdminProcedure[],
  statusId: string,
  dem: AeDemarchesPersisted,
  creationYear: number | null,
  calendarYear: number
): AdminProcedure[] {
  const desired = buildAeAutoProcedures({ statusId, dem, creationYear, calendarYear });
  const without = prev.filter((p) => !isAeManagedAutoProcedure(p, statusId));
  const existingAe = prev.filter((p) => isAeManagedAutoProcedure(p, statusId));
  const byKey = new Map<AeManagedTemplateKey, AdminProcedure>();
  for (const p of existingAe) {
    const k = p.templateKey as AeManagedTemplateKey | undefined;
    if (!k) continue;
    byKey.set(k, p);
  }
  const merged: AdminProcedure[] = [];
  for (const fresh of desired) {
    const k = fresh.templateKey as AeManagedTemplateKey | undefined;
    if (!k) continue;
    const ex = byKey.get(k);
    if (ex) {
      merged.push({
        ...ex,
        label: fresh.label,
        organisme: fresh.organisme,
        recurrence: fresh.recurrence,
        templateKey: fresh.templateKey,
        isAutoGenerated: true,
        statutJuridiqueId: statusId,
        dateLimite: fresh.dateLimite,
      });
      byKey.delete(k);
    } else {
      merged.push(fresh);
    }
  }
  return [...without, ...merged];
}

export function normalizeAeDemarchesFromData(raw: unknown): AeDemarchesPersisted {
  if (!raw || typeof raw !== "object") return { ...DEFAULT_AE_DEMARCHES };
  const o = raw as Record<string, unknown>;
  const cadence = o.declarationCadence === "monthly" ? "monthly" : "quarterly";
  const mode = o.socialFiscalMode === "liberatoire" ? "liberatoire" : "micro_social";
  const ca = o.cfeCurrentYearCaEuros;
  return {
    declarationCadence: cadence,
    cfeCurrentYearCaEuros: typeof ca === "string" ? ca : ca != null ? String(ca) : undefined,
    cfeMarkedExempt: o.cfeMarkedExempt === true,
    socialFiscalMode: mode,
  };
}
