import type { AdminProcedure } from "@/lib/sidekick-store";

export interface AssociationDemarchesPersisted {
  bureauRenewalEnabled: boolean;
  hasSubventions: boolean;
  hasEmployes: boolean;
  /** Toggle manuel quand ni subvention ni salarié */
  rapportActiviteEnabled: boolean;
  /** Date ISO de l'AGO (selon statuts) — remplace le 30 juin par défaut */
  agoDate?: string;
  /** Date ISO de fin d'exercice comptable — ajuste l'échéance du compte rendu */
  finExerciceDate?: string;
}

const ASSOC_TEMPLATE_KEYS = [
  "assoc_ago",
  "assoc_bureau_renewal",
  "assoc_rapport_activite",
] as const;
export type AssocManagedTemplateKey = (typeof ASSOC_TEMPLATE_KEYS)[number];

export const DEFAULT_ASSOCIATION_DEMARCHES: AssociationDemarchesPersisted = {
  bureauRenewalEnabled: false,
  hasSubventions: false,
  hasEmployes: false,
  rapportActiviteEnabled: false,
};

export function normalizeAssociationDemarchesFromData(
  raw: unknown
): AssociationDemarchesPersisted {
  if (!raw || typeof raw !== "object") return DEFAULT_ASSOCIATION_DEMARCHES;
  const r = raw as Partial<AssociationDemarchesPersisted>;
  return {
    bureauRenewalEnabled: Boolean(r.bureauRenewalEnabled),
    hasSubventions: Boolean(r.hasSubventions),
    hasEmployes: Boolean(r.hasEmployes),
    rapportActiviteEnabled: Boolean(r.rapportActiviteEnabled),
    agoDate: typeof r.agoDate === "string" ? r.agoDate : undefined,
    finExerciceDate: typeof r.finExerciceDate === "string" ? r.finExerciceDate : undefined,
  };
}

/** Prochain 30 juin ou 31 mars à venir (ISO YYYY-MM-DD). */
function nextAnnualIso(month: number, day: number): string {
  const today = new Date();
  const thisYear = new Date(today.getFullYear(), month - 1, day);
  const target =
    thisYear > today
      ? thisYear
      : new Date(today.getFullYear() + 1, month - 1, day);
  return target.toISOString().slice(0, 10);
}

function assocProcedure(args: {
  statusId: string;
  templateKey: AssocManagedTemplateKey;
  label: string;
  organisme?: string;
  dateLimiteIso: string;
}): AdminProcedure {
  return {
    id: crypto.randomUUID(),
    label: args.label,
    status: "a_faire",
    statutJuridiqueId: args.statusId,
    organisme: args.organisme,
    recurrence: "annual",
    templateKey: args.templateKey,
    isAutoGenerated: true,
    dateLimite: args.dateLimiteIso,
  };
}

export function rapportActiviteRequired(dem: AssociationDemarchesPersisted): boolean {
  return dem.hasSubventions || dem.hasEmployes;
}

/**
 * Retourne la date ISO 6 mois après la fin d'exercice.
 * Sans date renseignée : 6 mois après le 31 décembre (= 30 juin suivant).
 */
function sixMonthsAfterIso(finExerciceIso: string | undefined): string {
  const base = finExerciceIso?.trim()
    ? new Date(`${finExerciceIso}T12:00:00`)
    : (() => {
        const d = new Date();
        return new Date(d.getFullYear(), 11, 31); // 31 déc. de l'année en cours
      })();
  const due = new Date(base);
  due.setMonth(due.getMonth() + 6);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  if (due <= today) due.setFullYear(due.getFullYear() + 1);
  return due.toISOString().slice(0, 10);
}

export function buildAssociationAutoProcedures(args: {
  statusId: string;
  dem: AssociationDemarchesPersisted;
}): AdminProcedure[] {
  const { statusId, dem } = args;
  const list: AdminProcedure[] = [];

  const agoIso = dem.agoDate ?? nextAnnualIso(6, 30);
  list.push(
    assocProcedure({
      statusId,
      templateKey: "assoc_ago",
      label: "Assemblée Générale Ordinaire (AGO)",
      organisme: "Interne",
      dateLimiteIso: agoIso,
    })
  );

  if (dem.bureauRenewalEnabled) {
    list.push(
      assocProcedure({
        statusId,
        templateKey: "assoc_bureau_renewal",
        label: "Renouvellement / déclaration du bureau en préfecture",
        organisme: "Préfecture",
        dateLimiteIso: agoIso,
      })
    );
  }

  if (rapportActiviteRequired(dem) || dem.rapportActiviteEnabled) {
    const rapportIso = sixMonthsAfterIso(dem.finExerciceDate);
    list.push(
      assocProcedure({
        statusId,
        templateKey: "assoc_rapport_activite",
        label: "Compte rendu financier et bilan moral",
        organisme: "Interne",
        dateLimiteIso: rapportIso,
      })
    );
  }

  return list;
}

export function isAssociationManagedAutoProcedure(
  p: AdminProcedure,
  statusId: string
): p is AdminProcedure & { templateKey: AssocManagedTemplateKey } {
  if (p.statutJuridiqueId !== statusId) return false;
  if (!p.isAutoGenerated) return false;
  const tk = p.templateKey as string | undefined;
  return Boolean(tk && (ASSOC_TEMPLATE_KEYS as readonly string[]).includes(tk));
}

export function mergeSyncedAssociationAutoProcedures(
  prev: AdminProcedure[],
  statusId: string,
  dem: AssociationDemarchesPersisted
): AdminProcedure[] {
  const desired = buildAssociationAutoProcedures({ statusId, dem });
  const without = prev.filter((p) => !isAssociationManagedAutoProcedure(p, statusId));
  const existingAssoc = prev.filter((p) => isAssociationManagedAutoProcedure(p, statusId));
  const byKey = new Map<AssocManagedTemplateKey, AdminProcedure>();
  for (const p of existingAssoc) {
    const k = p.templateKey as AssocManagedTemplateKey | undefined;
    if (k) byKey.set(k, p);
  }
  const merged = desired.map((d) => {
    const existing = byKey.get(d.templateKey as AssocManagedTemplateKey);
    if (!existing) return d;
    return { ...d, id: existing.id, status: existing.status, dateLimite: existing.dateLimite };
  });
  return [...without, ...merged];
}
