import type { AdminProcedure } from "@/lib/sidekick-store";
import type { ProcedureRecurrence } from "@/modules/admin/data/procedure-templates";

export interface IntermittentDemarchesPersisted {
  /** Date ISO anniversaire / réexamen des droits — pilote la vérification des 507 h */
  anniversaryDate?: string;
  /** Affilié à la caisse des Congés Spectacles → démarche annuelle proposée */
  congesSpectaclesEnabled: boolean;
  /** Suivi de la visite médicale CMB (médecine du travail, tous les 2 ans) */
  medecineTravailEnabled: boolean;
  /** Date ISO de la dernière visite médicale CMB (pour calculer la prochaine) */
  lastMedecineVisitDate?: string;
  /** Inscrit à l'AFDAS (formation professionnelle) → rappel annuel */
  afdasEnabled: boolean;
}

const INTERMITTENT_TEMPLATE_KEYS = [
  "intermittent_actualisation",
  "intermittent_507h_check",
  "intermittent_conges_spectacles",
  "intermittent_medecine_travail",
  "intermittent_afdas",
] as const;
export type IntermittentManagedTemplateKey = (typeof INTERMITTENT_TEMPLATE_KEYS)[number];

export const INTERMITTENT_HOURS_TARGET = 507;

export const DEFAULT_INTERMITTENT_DEMARCHES: IntermittentDemarchesPersisted = {
  congesSpectaclesEnabled: false,
  medecineTravailEnabled: true,
  afdasEnabled: false,
};

export function normalizeIntermittentDemarchesFromData(
  raw: unknown
): IntermittentDemarchesPersisted {
  if (!raw || typeof raw !== "object") return DEFAULT_INTERMITTENT_DEMARCHES;
  const r = raw as Partial<IntermittentDemarchesPersisted>;
  return {
    anniversaryDate: typeof r.anniversaryDate === "string" ? r.anniversaryDate : undefined,
    congesSpectaclesEnabled: Boolean(r.congesSpectaclesEnabled),
    medecineTravailEnabled: r.medecineTravailEnabled !== false,
    lastMedecineVisitDate:
      typeof r.lastMedecineVisitDate === "string" ? r.lastMedecineVisitDate : undefined,
    afdasEnabled: Boolean(r.afdasEnabled),
  };
}

/** Total d'heures sur les 12 derniers mois glissants — même logique que le dashboard Intermittence. */
export function cumulativeHoursLast12Months(
  missions: { date: string; hours: number }[]
): number {
  const now = new Date();
  const cm = now.getMonth();
  const cy = now.getFullYear();
  return missions.reduce((sum, m) => {
    const d = new Date(m.date);
    if (Number.isNaN(d.getTime())) return sum;
    const monthsDiff = (cy - d.getFullYear()) * 12 + (cm - d.getMonth());
    if (monthsDiff >= 0 && monthsDiff < 12) return sum + (m.hours || 0);
    return sum;
  }, 0);
}

/** Prochaine occurrence à venir du jour/mois d'une date ISO (YYYY-MM-DD). */
function nextAnnualFromIso(iso: string): string {
  const [y, m, d] = iso.split("-").map((p) => parseInt(p, 10));
  if (!Number.isFinite(m) || !Number.isFinite(d)) return iso;
  void y;
  const today = new Date();
  const thisYear = new Date(today.getFullYear(), m - 1, d);
  const target = thisYear > today ? thisYear : new Date(today.getFullYear() + 1, m - 1, d);
  return target.toISOString().slice(0, 10);
}

/** Prochain jour/mois fixe à venir (ISO YYYY-MM-DD). */
function nextAnnualIso(month: number, day: number): string {
  const today = new Date();
  const thisYear = new Date(today.getFullYear(), month - 1, day);
  const target = thisYear > today ? thisYear : new Date(today.getFullYear() + 1, month - 1, day);
  return target.toISOString().slice(0, 10);
}

function nextDueIso(daysAhead: number): string {
  const d = new Date();
  d.setDate(d.getDate() + daysAhead);
  return d.toISOString().slice(0, 10);
}

/** Prochaine visite médicale : 2 ans après la dernière. */
function nextMedecineVisitIso(lastVisitIso: string): string {
  const last = new Date(lastVisitIso);
  if (Number.isNaN(last.getTime())) return nextDueIso(365 * 2);
  last.setFullYear(last.getFullYear() + 2);
  return last.toISOString().slice(0, 10);
}

function intProcedure(args: {
  statusId: string;
  templateKey: IntermittentManagedTemplateKey;
  label: string;
  organisme?: string;
  recurrence: ProcedureRecurrence;
  dateLimiteIso: string;
}): AdminProcedure {
  return {
    id: crypto.randomUUID(),
    label: args.label,
    status: "a_faire",
    statutJuridiqueId: args.statusId,
    organisme: args.organisme,
    recurrence: args.recurrence,
    templateKey: args.templateKey,
    isAutoGenerated: true,
    dateLimite: args.dateLimiteIso,
  };
}

export function buildIntermittentAutoProcedures(args: {
  statusId: string;
  dem: IntermittentDemarchesPersisted;
}): AdminProcedure[] {
  const { statusId, dem } = args;
  const list: AdminProcedure[] = [];

  // Actualisation mensuelle — réflexe systématique, indépendant de la date anniversaire.
  list.push(
    intProcedure({
      statusId,
      templateKey: "intermittent_actualisation",
      label: "Actualisation mensuelle France Travail",
      organisme: "France Travail",
      recurrence: "monthly",
      dateLimiteIso: nextDueIso(30),
    })
  );

  // Vérification des 507 h, calée sur la date anniversaire.
  if (dem.anniversaryDate) {
    list.push(
      intProcedure({
        statusId,
        templateKey: "intermittent_507h_check",
        label: "Vérifier les 507 h avant la date anniversaire",
        organisme: "France Travail",
        recurrence: "annual",
        dateLimiteIso: nextAnnualFromIso(dem.anniversaryDate),
      })
    );
  }

  // Congés Spectacles — campagne annuelle (ouverture habituelle au printemps).
  if (dem.congesSpectaclesEnabled) {
    list.push(
      intProcedure({
        statusId,
        templateKey: "intermittent_conges_spectacles",
        label: "Demander les Congés Spectacles",
        organisme: "Congés Spectacles",
        recurrence: "annual",
        dateLimiteIso: nextAnnualIso(4, 30),
      })
    );
  }

  // Visite médicale CMB — obligatoire tous les 2 ans.
  if (dem.medecineTravailEnabled) {
    const medDue = dem.lastMedecineVisitDate
      ? nextMedecineVisitIso(dem.lastMedecineVisitDate)
      : nextDueIso(365 * 2);
    list.push(
      intProcedure({
        statusId,
        templateKey: "intermittent_medecine_travail",
        label: "Visite médicale — médecine du travail (CMB)",
        organisme: "CMB Médecine du Travail",
        recurrence: "biannual",
        dateLimiteIso: medDue,
      })
    );
  }

  // AFDAS — rappel annuel pour les droits à la formation.
  if (dem.afdasEnabled) {
    list.push(
      intProcedure({
        statusId,
        templateKey: "intermittent_afdas",
        label: "Vérifier / activer les droits AFDAS (formation)",
        organisme: "AFDAS",
        recurrence: "annual",
        dateLimiteIso: nextAnnualIso(9, 30),
      })
    );
  }

  return list;
}

export function isIntermittentManagedAutoProcedure(
  p: AdminProcedure,
  statusId: string
): p is AdminProcedure & { templateKey: IntermittentManagedTemplateKey } {
  if (p.statutJuridiqueId !== statusId) return false;
  if (!p.isAutoGenerated) return false;
  const tk = p.templateKey as string | undefined;
  return Boolean(tk && (INTERMITTENT_TEMPLATE_KEYS as readonly string[]).includes(tk));
}

export function mergeSyncedIntermittentAutoProcedures(
  prev: AdminProcedure[],
  statusId: string,
  dem: IntermittentDemarchesPersisted
): AdminProcedure[] {
  const desired = buildIntermittentAutoProcedures({ statusId, dem });
  const without = prev.filter((p) => !isIntermittentManagedAutoProcedure(p, statusId));
  const existing = prev.filter((p) => isIntermittentManagedAutoProcedure(p, statusId));
  const byKey = new Map<IntermittentManagedTemplateKey, AdminProcedure>();
  for (const p of existing) {
    const k = p.templateKey as IntermittentManagedTemplateKey | undefined;
    if (k) byKey.set(k, p);
  }
  const merged = desired.map((d) => {
    const ex = byKey.get(d.templateKey as IntermittentManagedTemplateKey);
    if (!ex) return d;
    return { ...d, id: ex.id, status: ex.status, dateLimite: ex.dateLimite };
  });
  return [...without, ...merged];
}
