import type { AdminProcedure, AdminStatus, AdminStatusType } from "@/lib/sidekick-store";
import {
  getTemplatesForStatusType,
  isTemplateAvailable,
  templateLabel,
  templateRecurrence,
  type AdminProcedureTemplate,
  type AeCadence,
} from "@/modules/admin/data/procedure-templates";

/**
 * Ce que l'artiste choisit pour ses démarches, stocké dans `data.demarches` du
 * statut. Deux réglages seulement — tout le reste est décidé par le catalogue.
 */
export interface StatusDemarchesSelection {
  /** Clés des modèles cochés. */
  selectedKeys: string[];
  /** Auto-entrepreneur : cadence de déclaration. */
  aeCadence: AeCadence;
  /** Intermittent : date anniversaire de réexamen des droits (ISO). Facultative. */
  anniversaryDate?: string;
}

export const DEFAULT_AE_CADENCE: AeCadence = "quarterly";

// ─── Échéances ───────────────────────────────────────────────────────────────

function isoInDays(days: number): string {
  const d = new Date();
  d.setHours(12, 0, 0, 0);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

/** Prochaine occurrence à venir d'un jour/mois fixe. */
function nextFixedAnnualIso(month: number, day: number): string {
  const today = new Date();
  today.setHours(12, 0, 0, 0);
  const thisYear = new Date(today.getFullYear(), month - 1, day, 12);
  const target =
    thisYear > today ? thisYear : new Date(today.getFullYear() + 1, month - 1, day, 12);
  return target.toISOString().slice(0, 10);
}

/** Prochaine occurrence à venir du jour/mois d'une date ISO saisie. */
function nextAnnualFromIso(iso: string): string | null {
  const [, m, d] = iso.split("-").map((p) => parseInt(p, 10));
  if (!Number.isFinite(m) || !Number.isFinite(d)) return null;
  return nextFixedAnnualIso(m, d);
}

function firstDueIso(
  template: AdminProcedureTemplate,
  selection: StatusDemarchesSelection
): string | null {
  const { firstDue } = template;
  switch (firstDue.kind) {
    case "inDays":
      return isoInDays(firstDue.days);
    case "fixedAnnual":
      return nextFixedAnnualIso(firstDue.month, firstDue.day);
    case "everyTwoYears":
      return isoInDays(365 * 2);
    case "anniversary": {
      const anniversary = selection.anniversaryDate?.trim();
      if (!anniversary) return null;
      return nextAnnualFromIso(anniversary);
    }
  }
}

// ─── Construction ────────────────────────────────────────────────────────────

function procedureFromTemplate(
  template: AdminProcedureTemplate,
  statusId: string,
  selection: StatusDemarchesSelection
): AdminProcedure | null {
  const dateLimite = firstDueIso(template, selection);
  if (!dateLimite) return null;
  return {
    id: crypto.randomUUID(),
    label: templateLabel(template, selection.aeCadence),
    status: "a_faire",
    statutJuridiqueId: statusId,
    organisme: template.organisme,
    recurrence: templateRecurrence(template, selection.aeCadence),
    templateKey: template.key,
    isAutoGenerated: true,
    dateLimite,
  };
}

/** Modèles réellement proposables pour un statut, dans l'ordre du catalogue. */
export function availableTemplates(
  statusType: AdminStatusType,
  selection: Pick<StatusDemarchesSelection, "anniversaryDate">
): AdminProcedureTemplate[] {
  return getTemplatesForStatusType(statusType).filter((t) =>
    isTemplateAvailable(t, selection)
  );
}

/** Sélection par défaut d'un type de statut, à la première ouverture du formulaire. */
export function defaultSelectionForType(
  statusType: AdminStatusType
): StatusDemarchesSelection {
  return {
    selectedKeys: getTemplatesForStatusType(statusType)
      .filter((t) => t.defaultChecked)
      .map((t) => t.key),
    aeCadence: DEFAULT_AE_CADENCE,
  };
}

/** Création d'un statut : construit les démarches cochées. */
export function buildProceduresForSelection(args: {
  statusId: string;
  statusType: AdminStatusType;
  selection: StatusDemarchesSelection;
}): AdminProcedure[] {
  const { statusId, statusType, selection } = args;
  const selected = new Set(selection.selectedKeys);
  return availableTemplates(statusType, selection)
    .filter((t) => selected.has(t.key))
    .map((t) => procedureFromTemplate(t, statusId, selection))
    .filter((p): p is AdminProcedure => p !== null);
}

/**
 * Édition d'un statut : ajoute les cases nouvellement cochées, retire les
 * décochées, et met à jour libellé, organisme et récurrence des conservées.
 *
 * Ce qui n'est **jamais** écrasé : l'échéance et l'avancement d'une démarche
 * déjà créée — l'artiste a pu déplacer la date ou la marquer terminée. Les
 * démarches créées à la main (`isAutoGenerated` absent) ne sont pas touchées.
 */
export function syncProceduresForSelection(
  prev: AdminProcedure[],
  args: { statusId: string; statusType: AdminStatusType; selection: StatusDemarchesSelection }
): AdminProcedure[] {
  const { statusId, statusType, selection } = args;
  const selected = new Set(selection.selectedKeys);
  const templates = availableTemplates(statusType, selection);

  const managedKeys = new Set(
    getTemplatesForStatusType(statusType).map((t) => t.key)
  );
  const isManaged = (p: AdminProcedure) =>
    p.statutJuridiqueId === statusId &&
    Boolean(p.isAutoGenerated) &&
    typeof p.templateKey === "string" &&
    managedKeys.has(p.templateKey);

  const untouched = prev.filter((p) => !isManaged(p));
  const existingByKey = new Map<string, AdminProcedure>();
  for (const p of prev) {
    if (isManaged(p) && typeof p.templateKey === "string") {
      existingByKey.set(p.templateKey, p);
    }
  }

  const kept: AdminProcedure[] = [];
  for (const template of templates) {
    if (!selected.has(template.key)) continue;
    const existing = existingByKey.get(template.key);
    if (existing) {
      kept.push({
        ...existing,
        label: templateLabel(template, selection.aeCadence),
        organisme: template.organisme,
        recurrence: templateRecurrence(template, selection.aeCadence),
      });
      continue;
    }
    const fresh = procedureFromTemplate(template, statusId, selection);
    if (fresh) kept.push(fresh);
  }

  // Une démarche dont le modèle n'est plus proposable (date anniversaire
  // effacée) sort de `templates`, donc n'est pas reprise : elle est retirée
  // comme si la case avait été décochée.
  return [...untouched, ...kept];
}

// ─── Compatibilité avec les statuts enregistrés avant la refonte ─────────────

function asRecord(value: unknown): Record<string, unknown> | null {
  if (!value || typeof value !== "object") return null;
  return value as Record<string, unknown>;
}

/**
 * Statuts enregistrés avant la refonte : convertit les anciens blobs
 * `data.aeDemarches` / `associationDemarches` / `intermittentDemarches` en
 * sélection de clés. La prochaine sauvegarde écrit le nouveau format.
 *
 * Un statut sans aucun de ces blobs retombe sur les `defaultChecked` du
 * catalogue.
 */
export function readDemarchesSelection(status: {
  type: AdminStatusType;
  data?: Record<string, unknown>;
}): StatusDemarchesSelection {
  const data = status.data ?? {};

  const current = asRecord(data.demarches);
  if (current && Array.isArray(current.selectedKeys)) {
    return {
      selectedKeys: (current.selectedKeys as unknown[]).filter(
        (k): k is string => typeof k === "string"
      ),
      aeCadence: current.aeCadence === "monthly" ? "monthly" : DEFAULT_AE_CADENCE,
      anniversaryDate:
        typeof current.anniversaryDate === "string" ? current.anniversaryDate : undefined,
    };
  }

  const legacyAe = asRecord(data.aeDemarches);
  if (status.type === "auto_entrepreneur" && legacyAe) {
    const keys: string[] = ["ae_declaration_ca"];
    if (legacyAe.cfeMarkedExempt !== true) keys.push("ae_cfe");
    if (legacyAe.socialFiscalMode === "liberatoire") keys.push("ae_versement_liberatoire");
    return {
      selectedKeys: keys,
      aeCadence: legacyAe.declarationCadence === "monthly" ? "monthly" : DEFAULT_AE_CADENCE,
    };
  }

  const legacyAssoc = asRecord(data.associationDemarches);
  if (status.type === "association_1901" && legacyAssoc) {
    const keys: string[] = ["assoc_ago"];
    if (legacyAssoc.bureauRenewalEnabled === true) keys.push("assoc_bureau_renewal");
    if (
      legacyAssoc.hasSubventions === true ||
      legacyAssoc.hasEmployes === true ||
      legacyAssoc.rapportActiviteEnabled === true
    ) {
      keys.push("assoc_rapport_activite");
    }
    return { selectedKeys: keys, aeCadence: DEFAULT_AE_CADENCE };
  }

  const legacyIntermittent = asRecord(data.intermittentDemarches);
  if (status.type === "intermittent" && legacyIntermittent) {
    const anniversaryDate =
      typeof legacyIntermittent.anniversaryDate === "string"
        ? legacyIntermittent.anniversaryDate
        : undefined;
    const keys: string[] = ["intermittent_actualisation"];
    if (anniversaryDate?.trim()) keys.push("intermittent_507h_check");
    if (legacyIntermittent.congesSpectaclesEnabled === true) {
      keys.push("intermittent_conges_spectacles");
    }
    // Historiquement coché par défaut, contrairement au catalogue.
    if (legacyIntermittent.medecineTravailEnabled !== false) {
      keys.push("intermittent_medecine_travail");
    }
    if (legacyIntermittent.afdasEnabled === true) keys.push("intermittent_afdas");
    return { selectedKeys: keys, aeCadence: DEFAULT_AE_CADENCE, anniversaryDate };
  }

  return defaultSelectionForType(status.type);
}

/** Le blob à écrire dans `data.demarches` du statut. */
export function serializeDemarchesSelection(
  selection: StatusDemarchesSelection
): Record<string, unknown> {
  return {
    selectedKeys: selection.selectedKeys,
    aeCadence: selection.aeCadence,
    ...(selection.anniversaryDate?.trim()
      ? { anniversaryDate: selection.anniversaryDate.trim() }
      : {}),
  };
}

/** Les anciens blobs, retirés de `data` à la prochaine sauvegarde. */
export function stripLegacyDemarchesBlobs(
  data: Record<string, unknown>
): Record<string, unknown> {
  const {
    aeDemarches: _ae,
    associationDemarches: _assoc,
    intermittentDemarches: _int,
    ...rest
  } = data;
  void _ae;
  void _assoc;
  void _int;
  return rest;
}

/** Statuts existants inclus : type utilisé par `readDemarchesSelection`. */
export type ReadableStatus = Pick<AdminStatus, "type" | "data">;
