"use client";

import { useEffect, useState } from "react";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select";
import { DatePicker } from "@/components/ui/date-picker";

type TaskCategory =
  | "Live"
  | "Phono"
  | "Edition"
  | "Revenus"
  | "Marketing"
  | "Admin"
  | "Perso";

type TaskPriority = "low" | "medium" | "high";

type TaskStatus = "todo" | "in-progress" | "done";

interface Task {
  id: string;
  title: string;
  description: string;
  deadline: string;
  priority: TaskPriority;
  category: TaskCategory;
  status: TaskStatus;
  completed: boolean;
  isAutoGenerated?: boolean;
  linkedEventId?: string;
}

interface TaskModalProps {
  open: boolean;
  onClose: () => void;
  onSave: (task: Omit<Task, "id">) => void;
  task: Task | null;
}

export function TaskModal({ open, onClose, onSave, task }: TaskModalProps) {
  const [formData, setFormData] = useState<{
    title: string;
    description: string;
    deadline: string;
    priority: TaskPriority;
    category: TaskCategory;
    status: TaskStatus;
    completed: boolean;
  }>({
    title: "",
    description: "",
    deadline: "",
    priority: "medium",
    category: "Live",
    status: "todo",
    completed: false
  });

  useEffect(() => {
    if (task) {
      setFormData({
        title: task.title,
        description: task.description,
        deadline: task.deadline,
        priority: task.priority,
        category: task.category,
        status: task.status,
        completed: task.completed
      });
    } else {
      setFormData({
        title: "",
        description: "",
        deadline: "",
        priority: "medium",
        category: "Live",
        status: "todo",
        completed: false
      });
    }
  }, [task, open]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSave(formData);
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>
            {task ? "Modifier la tâche" : "Ajouter une nouvelle tâche"}
          </DialogTitle>
          <DialogDescription>
            {task
              ? "Modifiez les détails de la tâche."
              : "Ajoutez une nouvelle tâche à votre liste."}
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit}>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="title">Titre</Label>
              <Input
                id="title"
                value={formData.title}
                onChange={(e) =>
                  setFormData({ ...formData, title: e.target.value })
                }
                placeholder="Titre de la tâche"
                required
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="description">Description</Label>
              <Textarea
                id="description"
                value={formData.description}
                onChange={(e) =>
                  setFormData({ ...formData, description: e.target.value })
                }
                placeholder="Description de la tâche"
                rows={3}
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="deadline">Échéance</Label>
              <DatePicker
                value={formData.deadline}
                onChange={(date) =>
                  setFormData({ ...formData, deadline: date })
                }
              />
            </div>

            <div className="space-y-2">
              <Label htmlFor="priority">Priorité</Label>
              <Select
                value={formData.priority}
                onValueChange={(value: TaskPriority) =>
                  setFormData({ ...formData, priority: value })
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Sélectionner la priorité" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="low">Basse</SelectItem>
                  <SelectItem value="medium">Moyenne</SelectItem>
                  <SelectItem value="high">Haute</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <Label htmlFor="category">Catégorie</Label>
              <Select
                value={formData.category}
                onValueChange={(
                  value: TaskCategory
                ) =>
                  setFormData({ ...formData, category: value })
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Sélectionner la catégorie" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Live">Live</SelectItem>
                  <SelectItem value="Phono">Phono</SelectItem>
                  <SelectItem value="Edition">Edition</SelectItem>
                  <SelectItem value="Revenus">Revenus</SelectItem>
                  <SelectItem value="Marketing">Marketing</SelectItem>
                  <SelectItem value="Admin">Admin</SelectItem>
                  <SelectItem value="Perso">Perso</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <DialogFooter>
            <Button type="button" variant="outline" onClick={onClose}>
              Annuler
            </Button>
            <Button type="submit">Enregistrer</Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

